### ISSUE TITLE
Genscript fails on Linux and Windows

### ISSUE THREAD

**Issue by horzoli** [ericsson-mts/mts#21]
Hi,

if I try to generate an MTS script from a capture file it fails on Windows and on Linux too with different errors:
Given the following command:
genscript.bat SIP:172.16.74.112:5060 ..\tutorial\genscript\URI_DISCOV_01.pcap test_mcdata.xml

on Win10, I get the following exception:

-------- GENSCRIPT -------------------------------------------------------
START => capture file: ..\tutorial\genscript\URI_DISCOV_01.pcap
CAPTURE filter: => SIP:172.16.74.112:5060
EXCEPTION => java.net.BindException: Cannot assign requested address: Cannot bind
java.net.BindException: Cannot assign requested address: Cannot bind
        at java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
        at java.net.DualStackPlainDatagramSocketImpl.bind0(Unknown Source)
        at java.net.AbstractPlainDatagramSocketImpl.bind(Unknown Source)
        at java.net.DatagramSocket.bind(Unknown Source)
        at java.net.DatagramSocket.<init>(Unknown Source)
        at com.devoteam.srit.xmlloader.udp.bio.ListenpointUdpBIO.create(ListenpointUdpBIO.java:67)
        at com.devoteam.srit.xmlloader.udp.ListenpointUdp.create(ListenpointUdp.java:143)
        at com.devoteam.srit.xmlloader.core.protocol.Listenpoint.create(Listenpoint.java:314)
        at com.devoteam.srit.xmlloader.core.protocol.Stack.createListenpoint(Stack.java:427)
        at com.devoteam.srit.xmlloader.core.protocol.Stack.initializePrivate(Stack.java:256)
        at com.devoteam.srit.xmlloader.core.protocol.Stack.<init>(Stack.java:237)
        at com.devoteam.srit.xmlloader.core.protocol.Stack.<init>(Stack.java:159)
        at com.devoteam.srit.xmlloader.sip.StackSipCommon.<init>(StackSipCommon.java:70)
        at com.devoteam.srit.xmlloader.sip.light.StackSip.<init>(StackSip.java:54)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at com.devoteam.srit.xmlloader.core.protocol.StackFactory.getStack(StackFactory.java:119)
        at com.devoteam.srit.xmlloader.genscript.genscriptCmd.main(genscriptCmd.java:132)

Then the same command on Redhat 7.5 gives the follwong message and then stucks:

atlas@nginlab52:/data4/workspace/horzoli/MTS_Home/bin$ ./genscript.sh SIP:172.16.74.112:5060 ../../URI_DISCOV_01.pcap testout.xml
-------- GENSCRIPT -------------------------------------------------------
START => capture file: ../../URI_DISCOV_01.pcap
CAPTURE filter: => SIP:172.16.74.112:5060
Thread[Thread-3,5,main]
java.lang.InstantiationException: jpcap.packet.DatalinkPacket
        at jpcap.JpcapCaptor.processPacket(Native Method)
        at com.devoteam.srit.xmlloader.core.protocol.probe.PJpcapThread.run(PJpcapThread.java:198)
        at com.devoteam.srit.xmlloader.core.ThreadRunner.run(ThreadRunner.java:59)

**Comment by msrpub** [comment]
Anyone found a solution for this?
Is genscript still being maintained and followed in some other repository?
