### ISSUE TITLE
can not receive response for messages sent on an sctp channel

### ISSUE THREAD

**Issue by fabiozamperini** [ericsson-mts/mts#30]
Using mts 6.5.1 

I'm trying to send SIP INVITEs through an SCTP multihoming channel with the following sequence

<openChannelSIP name="channelUAC" localHost="[localHostSIP(0)],[localHostSIP_sec(0)]" localPort="[localPortSIP_client(0)]" remoteHost="[remoteHostSIP(0)]" remotePort="[remotePortSIP(0)]" transport="SCTP">
<sendMessageSIP name="initial INVITE" channel="channelUAC" remoteHost="[remoteHostSIP(0)]" remotePort="[remotePortSIP(0)]" transport="SCTP">

100 trying is routed correctly to originating scenario, but subsesuent responses results in a NullPointerException

java.lang.NullPointerException
        at com.devoteam.srit.xmlloader.sip.MsgSipCommon.getResponseTransactionId(MsgSipCommon.java:80)
        at com.devoteam.srit.xmlloader.sip.StackSipCommon.doReceiveMessage(StackSipCommon.java:188)
        at com.devoteam.srit.xmlloader.core.protocol.Stack$1.run(Stack.java:917)

if i send the same message in SCTP avoiding channel indication in send message 
with the following:
<sendMessageSIP name="initial INVITE" remoteHost="[remoteHostSIP(0)]" remotePort="[remotePortSIP(0)]" transport="SCTP">

a new channel is created automatically and responses appears to be managed correctly in this case
therefore in this way i have no longer the option to choose source IPs and port for the SCTP channel, so i can not have the wanted multihoming configuration (mts use all available address and a random source port in this case)

what should be the right approach ?
am i missing something ?

**Comment by fabiozamperini** [comment]
fixed removing "this.getListenpoint().getName()" from related lines in MsgSipCommon.java and rebuilding the git snapshot
don't know if is the right solution but seems to work for me
